Ajout de segment de plateforme
tchapgouv/matrix-rageshake-crisp pull request #36
Opened 2024-02-06 17:23 UTC by NicolasBuquet

Fix #11

2024-02-07 09:29 UTC, odelcroi commented on src/job_process_all_incoming_messages.py
> +        segments = [segments, platform]
je pense que cela va créeer une liste imbriquée, à vérifier avec un test unitaire

2024-02-07 09:31 UTC, odelcroi commented on src/job_process_invalid_rageshake.py
> +def extract_platform(message_content: str) -> Optional[str]:
un test unitaire pourrait etre ajouter dans https://github.com/tchapgouv/matrix-rageshake-crisp/blob/main/test_job_process_invalid_rageshake.py

2024-02-07 09:32 UTC, odelcroi requested changes
see

2024-02-07 14:44 UTC, NicolasBuquet commented on src/job_process_all_incoming_messages.py
> +        segments = [segments, platform]
Fixed by using `segments.append(platform)`

2024-02-07 16:02 UTC, NicolasBuquet commented on src/job_process_invalid_rageshake.py
> +def extract_platform(message_content: str) -> Optional[str]:
Done

2024-02-11 22:08 UTC, odelcroi approved these changes
lgtm

2024-02-11 22:10 UTC, odelcroi commented
would be great to apply this platform segments to all existing crisp issues

2024-02-12 13:52 UTC, merged